In [ ]:
%pip install scikit-learn

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_california_housing
# from sklearn.linear_model import LinearRegression
# from sklearn.metrics import r2_score, mean_squared_error
# from sklearn.model_selection import train_test_split

sns.set(style="whitegrid")
np.random.seed(42)

# Load the dataset
data = fetch_california_housing()
X_full = pd.DataFrame(data.data, columns=data.feature_names)
y_full = pd.Series(data.target, name="MedHouseVal")

print("Feature names:", list(X_full.columns))
print(f"X shape: {X_full.shape}")
print(f"y shape: {y_full.shape}")
X_full.head()

Feature names: ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']
X shape: (20640, 8)
y shape: (20640,)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25

In [9]:
X_full.shape
y_full.shape

(20640,)

In [22]:
X_full['Price']=y_full[:10000]

In [18]:
X_full.shape

(20640, 9)

In [23]:
X_full.tail()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,Price
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,NaN
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,NaN
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,NaN
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,NaN
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,NaN